src/Common/src/System/Threading/Tasks/BeginEndAwaitableAdapter.cs
src/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs
src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs
src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/ParallelLoopState.cs
src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/ParallelRangeManager.cs

Needed for https://github.com/mono/mono/pull/6672

use System.Diagnostics.Private instead of System.Diagnostics

---

src/System.Threading.Tasks/tests/Task/TaskCancelWaitTests.cs

https://github.com/mono/mono/issues/6920

Disable test TaskCancelWait1

---

src/Common/src/CoreLib/System/Runtime/CompilerServices/AsyncStateMachineAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/CompilerGeneratedAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/CompilerGlobalScopeAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/CustomConstantAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/DateTimeConstantAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/DecimalConstantAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/FixedAddressValueTypeAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/IndexerNameAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/IteratorStateMachineAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/ReferenceAssemblyAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/RuntimeCompatibilityAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/RuntimeWrappedException.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/StateMachineAttribute.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/UnsafeValueTypeAttribute.cs

https://github.com/mono/mono/pull/7118

Bring back [Serializable] for mono

---

src/System.Collections.Specialized/src/System/Collections/Specialized/NameObjectCollectionBase.cs
src/System.Collections.Specialized/src/System/Collections/Specialized/NameValueCollection.cs
src/System.Collections.Specialized/src/System/Collections/Specialized/StringDictionary.cs
src/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs
src/System.Runtime.Extensions/src/System/Collections/Hashtable.cs

Needed for https://github.com/mono/mono/pull/7478

Add 'partial' for several types for mono (Collections)

---

src/Common/tests/System/Xml/XmlCoreTest/MiscUtil.cs
src/Common/tests/System/Xml/XmlDiff/XmlDiff.cs
src/System.Private.Xml.Linq/src/System/Xml/Linq/XDeclaration.cs
src/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs

Related to https://github.com/mono/mono/issues/8122

[System.Xml.Linq] add temporary conditional workaround to fix build errors.

---

src/System.Net.Http/src/System/Net/Http/Headers/MediaTypeHeaderValue.cs

This reverts commit ea8a19620a95fdcf6089f0e30759b042aef86076.

Revert "Add 'using System.Text' for StringBuilderCache."

---

src/Native/Unix/Common/pal_compiler.h

Fixes https://github.com/mono/mono/issues/8815

Fix for GCC < 4.8 compilers

---

src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs

Depends on https://github.com/mono/mono/pull/8719

Enable test fixed by https://github.com/mono/mono/pull/8719

---

src/Common/src/CoreLib/System/Guid.cs

A mistake made in https://github.com/mono/corefx/pull/70

Fix Guid.TryFormat on mono

---

src/Native/Unix/Common/pal_config.h.in
src/Native/Unix/System.Native/pal_errno.c
src/Native/Unix/System.Native/pal_io.c
src/Native/Unix/System.Native/pal_maphardwaretype.c
src/Native/Unix/System.Native/pal_networking.c
src/Native/Unix/System.Native/pal_random.c

This is a manual cherry pick of the commit due to differences in
cmake files preventing a clean merge of the normal patch. The
commit applied can be found at:
dotnet/corefx@eedd1c2784fd1c597428187985df00567bc00f86
More work will likely need to be done as more is backported and PAL
changes. In addition, the submodule will need to be updated as well.
Hopefully AIX CI should light up after that though!

Attempt at AIX support for CoreFX PAL

---

src/Native/Unix/System.Native/pal_io.c

Needed by https://github.com/mono/mono/pull/7255

Use icall for blocking read call in Mono

---

src/Common/src/Microsoft/Win32/SafeHandles/SafeHandleCache.cs
src/System.Security.Cryptography.X509Certificates/src/Microsoft/Win32/SafeHandles/SafePasswordHandle.Unix.cs
src/System.Security.Cryptography.X509Certificates/src/Microsoft/Win32/SafeHandles/SafePasswordHandle.Windows.cs

This cherry-picks corefx PR https://github.com/dotnet/corefx/pull/30908, with a Mono-specific `System.Diagnostics.Private` addition.

Bring https://github.com/dotnet/corefx/pull/30908

---

src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs

Apparently I screwed something up the first time and the mcs build was still broken. Sorry about that :-(

Fix 6d9217c7c7f9c6fd979a100b77068ec49e5b9fff to actually compile with mcs.

---

src/Common/src/CoreLib/System/Reflection/CustomAttributeFormatException.cs

Relates to https://github.com/mono/mono/pull/9693

CustomAttributeFormatException: hide type forwarding attribute

---

src/Common/src/CoreLib/System/BitConverter.cs
src/Common/src/CoreLib/System/StringComparer.cs
src/Common/src/CoreLib/System/Threading/ThreadStartException.cs
src/Common/src/CoreLib/System/Version.cs

Needed for https://github.com/mono/mono/pull/9744

hide typeforwarders for mono

---

src/Common/src/CoreLib/System/Reflection/ConstructorInfo.cs

Relates to https://github.com/mono/mono/pull/9970

[ConstructorInfo] Include [Serializable] attribute on Mono

---

src/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.cs

Needed for https://github.com/mono/mono/pull/9855

Add HKEY_DYN_DATA to mono

---

src/Common/src/CoreLib/System/InvalidTimeZoneException.cs
src/Common/src/CoreLib/System/StringComparer.cs
src/Common/src/CoreLib/System/Threading/LockRecursionException.cs
src/Common/src/CoreLib/System/Threading/SemaphoreFullException.cs
src/Common/src/CoreLib/System/TimeZoneNotFoundException.cs

see https://github.com/mono/mono/pull/9744#issuecomment-416564792

Hide more TypeForwarders

---

src/Native/Unix/System.Native/pal_networking.c

[mono-2018-06] Fix compilation errors on Linux kernel \u003c 3.9 (SO_REUSEPORT is not defined)

---

src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs

Merge with https://github.com/mono/mono/pull/9766

[System.IO] Enable CoreFX FilesystemWatcher on Android

---

src/Common/src/CoreLib/System/Reflection/ParameterInfo.cs

Relates to https://github.com/mono/mono/pull/10661

[Reflection] Add Serializable attribute to ParameterInfo class

---

src/Common/src/CoreLib/System/Text/Encoding.cs

Merge with https://github.com/mono/mono/pull/10860

[corlib] Import System.Text.Encoding from CoreFX

---

src/Common/src/CoreLib/System/IO/MemoryStream.cs

Merge with https://github.com/mono/mono/pull/10864

[corlib] Import System.IO.MemoryStream from CoreFX

---

src/System.Runtime.Extensions/tests/System/BitConverterArray.cs
src/System.Runtime.Extensions/tests/System/BitConverterSpan.cs

see https://github.com/mono/mono/pull/10758

Ignore ConvertFromFloat and ConvertFromDouble tests on mono

---

src/System.Threading.Tasks/tests/CancellationTokenTests.cs

fixes `System.Threading.Tasks.Tests.CancellationTokenTests.DerivedCancellationTokenSource
failure` on mono interpreter
source of helper (used in mono runtime tests): https://github.com/mono/mono/blob/ed50d2560a403583edcf78b9b5e4653103544830/mono/mini/TestHelpers.cs

[tests] add finalizer helper to avoid false pinning

---

src/Common/src/CoreLib/System/Text/EncodingNLS.cs
src/Common/src/CoreLib/System/Text/Latin1Encoding.cs

see https://github.com/mono/mono/issues/10289

Make Latin1Encoding Serializable

---

src/Common/src/CoreLib/System/Text/EncodingNLS.cs
src/Common/src/CoreLib/System/Text/Latin1Encoding.cs

Backport of #154.
/cc @marek-safar @EgorBo
Description:
see https://github.com/mono/mono/issues/10289

[mono-2018-08] Make Latin1Encoding Serializable

---

src/System.Reflection/tests/ConstructorInfoTests.cs

Relates to https://github.com/mono/mono/pull/11028

[Reflection] Re-enable Invoke_OneDimensionalArray_NegativeLengths_ThrowsOverflowException test

---

src/System.Collections/tests/Generic/Comparers/EqualityComparer.Generic.Tests.cs

Backport of https://github.com/mono/corefx/commit/c1404821516f17b9d62645e3d9ebcadfb3151b0d 
for https://github.com/xamarin/xamarin-android/pull/2048

[2018-08] Disables failing test on mobile

---

src/System.Threading.Tasks/tests/CancellationTokenTests.cs

Backport of #156.
/cc @akoeplinger @lewurm
Description:
fixes `System.Threading.Tasks.Tests.CancellationTokenTests.DerivedCancellationTokenSource
failure` on mono interpreter
source of helper (used in mono runtime tests): https://github.com/mono/mono/blob/ed50d2560a403583edcf78b9b5e4653103544830/mono/mini/TestHelpers.cs

[mono-2018-08] [tests] add finalizer helper to avoid false pinning

---

src/Native/Unix/Common/pal_utilities.h
src/Native/Unix/System.Native/CMakeLists.txt
src/Native/Unix/System.Native/pal_console.c
src/Native/Unix/System.Native/pal_console.h
src/Native/Unix/System.Native/pal_mount.c
src/Native/Unix/System.Native/pal_mount.h
src/Native/Unix/System.Native/pal_networkchange.c
src/Native/Unix/System.Native/pal_networkchange.h
src/Native/Unix/System.Native/pal_process.c
src/Native/Unix/System.Native/pal_process.h
src/Native/Unix/System.Native/pal_runtimeinformation.c
src/Native/Unix/System.Native/pal_runtimeinformation.h
src/Native/Unix/System.Native/pal_string.c
src/Native/Unix/System.Native/pal_uid.c
src/Native/Unix/System.Native/pal_uid.h

Cherry-pick of https://github.com/dotnet/corefx/commit/9f00f554483802a1ac295ad6260557fb125e0b31
* Rename .cpp to .c
* Convert System.Native to C
* Address feedback

 Convert System.Native to C  (#30431)

---

src/System.IO/tests/BinaryWriter/BinaryWriter.WriteByteCharTests.cs

Merge with https://github.com/mono/mono/pull/10880

[corlib] Import System.IO.Stream/BufferedStream from CoreFX

---

src/System.Drawing.Primitives/src/System/Drawing/Color.cs
src/System.Drawing.Primitives/src/System/Drawing/Point.cs
src/System.Drawing.Primitives/src/System/Drawing/Rectangle.cs
src/System.Drawing.Primitives/src/System/Drawing/Size.cs
src/System.Drawing.Primitives/src/System/Drawing/SizeF.cs
src/System.Net.Primitives/src/System/Net/HttpVersion.cs
src/System.Net.Primitives/src/System/Net/IPAddress.cs
src/System.Private.Uri/src/System/IPv4AddressHelper.cs
src/System.Private.Uri/src/System/IPv6AddressHelper.cs

Needed for https://github.com/mono/mono/pull/11658
and for upcoming System.Net PR.

Mono specific changes for System.Drawing and System.Net

---

src/System.Runtime/tests/System/TypeTests.cs

Coordinate with fix in mono/mono#11725

Re-enable test for mono/mono#11684

---

src/Common/src/CoreLib/System/Runtime/CompilerServices/AsyncValueTaskMethodBuilder.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/ConfiguredValueTaskAwaitable.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/ValueTaskAwaiter.cs
src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs

Needed for https://github.com/mono/mono/issues/11731

Copy some Task-related files from corefx-mono-2018-06

---

src/System.Runtime/tests/System/TypeTests.netcoreapp.cs

Related issue https://github.com/mono/mono/issues/11693 is fixed in https://github.com/mono/mono/pull/11736

Re-enable test case from mono issue 11693

---

src/Common/src/CoreLib/System/Text/DecoderReplacementFallback.cs
src/Common/src/CoreLib/System/Text/EncoderReplacementFallback.cs

backport of https://github.com/mono/corefx/pull/204 and https://github.com/mono/corefx/pull/209

[2018-08] Fix Encoding serialization

---

src/Common/src/CoreLib/System/Text/DecoderReplacementFallback.cs
src/Common/src/CoreLib/System/Text/EncoderReplacementFallback.cs

Backport of #204 and #209
Also, please note - I've created `mono-2018-10` branch (`Latest commit fa2ff75  22 days ago`).

[2018-10] Fix Encoding serialization

---

src/Common/src/CoreLib/System/IO/StreamWriter.cs

Needed for https://github.com/mono/mono/pull/11783

[corlib] Import System.IO.TextWriter/StreamWriter from CoreFX

---

src/Native/Unix/System.Native/pal_io.c

Merged upstream. See dotnet/corefx#33935

Fix readdir_r on AIX

---

src/Common/src/Interop/OSX/Interop.EventStream.cs
src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs
src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs
src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs
src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs
src/System.IO.FileSystem.Watcher/tests/System.IO.FileSystem.Watcher.Tests.csproj
src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs
src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs

This PR brings the changes from https://github.com/dotnet/corefx/pull/33865.
In order to apply the latest OSX version of FileSystemWatcher I updated some related stuff a bit.

Bring changes from corefx 33865

---

src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs

Port of  https://github.com/dotnet/corefx/pull/34438

Port 34438 "Handle flowsuppressed context in FileSystemWatcher on OS" from dotnet/corefx

---

src/Native/Unix/System.Native/pal_io.c
src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEntry.Unix.cs

Fix ConvertDirent on AIX,  FileEnumerator with unknowns for symlink

---

src/Common/src/CoreLib/System/ComponentModel/DefaultValueAttribute.cs

Backport of https://github.com/mono/corefx/pull/235 to mono-2018-12 branch.

[Mono-2018-12] Add TypeConverter fallback to DefaultValueAttribute

---

src/Common/src/CoreLib/System/ComponentModel/DefaultValueAttribute.cs

Backport of https://github.com/mono/corefx/pull/235 to mono-2018-10 branch.

[Mono-2018-10] Add TypeConverter fallback to DefaultValueAttribute

---

src/Common/src/CoreLib/System/Globalization/DateTimeFormat.cs
src/Common/src/CoreLib/System/Globalization/DateTimeFormatInfo.cs
src/Common/src/CoreLib/System/Globalization/DateTimeParse.cs

Relates to https://github.com/mono/mono/pull/12556

Update datetime-related stuff to support Japanese era change

---

src/Common/src/CoreLib/System/Boolean.cs
src/Common/src/CoreLib/System/Byte.cs
src/Common/src/CoreLib/System/Char.cs
src/Common/src/CoreLib/System/IO/StreamWriter.cs
src/Common/src/CoreLib/System/IO/TextWriter.cs
src/Common/src/CoreLib/System/Int16.cs
src/Common/src/CoreLib/System/Int32.cs
src/Common/src/CoreLib/System/Int64.cs
src/Common/src/CoreLib/System/IntPtr.cs
src/Common/src/CoreLib/System/Numerics/Vector.cs
src/Common/src/CoreLib/System/Runtime/CompilerServices/RuntimeFeature.cs
src/Common/src/CoreLib/System/Runtime/InteropServices/HandleRef.cs
src/Common/src/CoreLib/System/Runtime/Serialization/SerializationInfoEnumerator.cs
src/Common/src/CoreLib/System/SByte.cs
src/Common/src/CoreLib/System/Threading/AsyncLocal.cs
src/Common/src/CoreLib/System/UInt16.cs
src/Common/src/CoreLib/System/UInt32.cs
src/Common/src/CoreLib/System/UInt64.cs
src/Common/src/CoreLib/System/UIntPtr.cs
src/System.ComponentModel.EventBasedAsync/src/System/ComponentModel/BackgroundWorker.cs
src/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/Serialization/RootDesignerSerializerAttribute.cs
src/System.ComponentModel.TypeConverter/src/System/ComponentModel/IComNativeDescriptorHandler.cs
src/System.Data.Common/src/System/Data/DataSet.cs
src/System.Data.Common/src/System/Data/DataSysAttribute.cs
src/System.Diagnostics.Tools/src/System/Diagnostics/CodeAnalysis/ExcludeFromCodeCoverageAttribute.cs
src/System.Runtime.Extensions/src/System/IO/BufferedStream.cs

Set of small changes to make Mono NS2.1 compatible, mostly copy-pasted from CoreFX-master.

NS2.1 changes

---

src/System.Runtime/tests/System/DecimalTests.cs

See CoreFX master: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/DecimalTests.cs#L794-L797

Fix Remainder_Invalid_TestData test

---

src/Native/Unix/System.Native/pal_io.c

Yes, AIX has different values.

Switch from asserts on POSIX_FADV_* to conversions

---

src/Common/src/CoreLib/System/HResults.cs

Adding constant for COR_E_AMBIGUOUSIMPLEMENTATION.

Adding constant for COR_E_AMBIGUOUSIMPLEMENTATION.

---

src/Common/src/Interop/Interop.Odbc.cs
src/System.Data.Odbc/src/System/Data/Odbc/OdbcConnection.cs

Should match dotnet/corefx#36710 with slight differences due to
divergences in the files.

Fix ODBC issues with UTF-16

---

src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs
src/Common/src/CoreLib/System/Memory.cs
src/Common/src/CoreLib/System/Range.cs
src/Common/src/CoreLib/System/ReadOnlyMemory.cs

```
Collection.cs 
Range.cs 
```
were fully copied from the dotnet/corefx master (I only removed the C# 8.0 nullability stuff)

Reflect latest NS2.1 changes

---

src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs

[monodroid] Enable building on win32

---

src/System.Data.Common/src/System/Data/Common/DbCommand.cs
src/System.Data.Common/src/System/Data/Common/DbConnection.cs
src/System.Data.Common/src/System/Data/Common/DbDataReader.cs
src/System.Data.Common/src/System/Data/Common/DbProviderFactory.cs
src/System.Data.Common/src/System/Data/Common/DbTransaction.cs

Copy recent NS2.1 related changes from the upstream.
Others will be handled in mono/mono

Sync recent NS2.1 changes

---

src/System.Linq.Queryable/src/System/Linq/EnumerableRewriter.cs

Fixes https://github.com/mono/mono/issues/15259

Add dependency tracking for linker to EnumerableRewriter. 

---

src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs

[mono-2019-08] Fix another bug in https://github.com/mono/mono/pull/16049

---

src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs

[mono-2019-06] Fix another bug in https://github.com/mono/mono/pull/16049

---

src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs

[mono-2019-02] Fix another bug in https://github.com/mono/mono/pull/16049

---

src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs

Backport of: https://github.com/dotnet/corefx/pull/41013

Pull in fsw fix that fixes https://github.com/dotnet/corefx/issues/40888

---

src/Common/src/CoreLib/System/Math.cs
src/System.Data.DataSetExtensions/src/System/Data/DataTableExtensions.cs
src/System.Memory/src/System/Buffers/ReadOnlySequence.cs
src/System.Memory/src/System/Buffers/ReadOnlySequence_helpers.cs
src/System.Memory/src/System/Buffers/StandardFormat.cs
src/System.Memory/src/System/Runtime/InteropServices/SequenceMarshal.cs

Mostly changes around System.Buffers and System.Data, mostly copy-pasted the whole files from the upstream.

Reflect NS21 changes

---

src/Common/src/CoreLib/System/Math.cs
src/System.Data.DataSetExtensions/src/System/Data/DataTableExtensions.cs
src/System.Memory/src/System/Buffers/ReadOnlySequence.cs
src/System.Memory/src/System/Buffers/ReadOnlySequence_helpers.cs
src/System.Memory/src/System/Buffers/StandardFormat.cs
src/System.Memory/src/System/Runtime/InteropServices/SequenceMarshal.cs

Mostly changes around System.Buffers and System.Data, mostly copy-pasted the whole files from the upstream.
Backport of #348.
/cc @akoeplinger @EgorBo

[mono-2019-08] Reflect NS21 changes

---

src/System.Memory/src/System/Runtime/InteropServices/SequenceMarshal.cs

Backport of #350.
/cc @akoeplinger @EgorBo

[master] [2019-06] Fix mcs build

---

src/System.Memory/src/System/Runtime/InteropServices/SequenceMarshal.cs

Backport of #350.
/cc @akoeplinger @EgorBo

[mono-2019-08] Fix mcs build

---

src/System.Memory/src/System/Buffers/ReadOnlySequence.cs
src/System.Memory/src/System/Buffers/ReadOnlySequence_helpers.cs

Remove the nullability annotations for now.

Fix ReadOnlySequence.cs build with mcs

---

src/System.Memory/src/System/Buffers/ReadOnlySequence.cs
src/System.Memory/src/System/Buffers/ReadOnlySequence_helpers.cs

Remove the nullability annotations for now.
Backport of #354.

[mono-2019-08] Fix ReadOnlySequence.cs build with mcs

---

src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs
src/System.Data.SqlClient/src/System/Data/SqlClient/SqlParameterHelper.cs
src/System.Data.SqlClient/tests/ManualTests/SQL/ParameterTest/SqlAdapterUpdateBatch.cs
src/System.Data.SqlClient/tests/ManualTests/System.Data.SqlClient.ManualTesting.Tests.csproj

Backport of https://github.com/dotnet/corefx/pull/29614
Fixes https://github.com/mono/mono/issues/14450

Backport SqlCommand Fix

---

src/Common/src/CoreLib/Interop/Unix/System.Native/Interop.Stat.cs
src/Common/src/Interop/Unix/System.Native/Interop.LChflags.cs
src/Common/src/Interop/Unix/System.Native/Interop.Stat.cs
src/Native/Unix/Common/pal_config.h.in
src/Native/Unix/System.Native/pal_io.c
src/Native/Unix/System.Native/pal_io.h
src/System.IO.FileSystem/src/System.IO.FileSystem.csproj
src/System.IO.FileSystem/src/System/IO/FileStatus.Unix.cs
src/System.IO.FileSystem/tests/Base/FileGetSetAttributes.cs
src/System.IO.FileSystem/tests/FileInfo/GetSetAttributes.cs

Backport of https://github.com/dotnet/corefx/pull/34560
Fixes https://github.com/mono/mono/issues/17304

Backport corefx osx hidden files

---

src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs
src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ConnectionReuse.cs

Mono-specific workaround of https://github.com/mono/mono/issues/17710.

Add workaround for #17710.

---

src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs
src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ConnectionReuse.cs

Mono-specific workaround of https://github.com/mono/mono/issues/17710.
Backport of #387.
/cc @baulig

[mono-2019-12] Add workaround for #17710.

---

src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs
src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ConnectionReuse.cs

Mono-specific workaround of https://github.com/mono/mono/issues/17710.
Backport of #387.
/cc @baulig

[mono-2019-10] Add workaround for #17710.

---

src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs
src/System.Data.SqlClient/tests/FunctionalTests/ExceptionTest.cs
src/System.Data.SqlClient/tests/FunctionalTests/SqlConnectionBasicTests.cs
src/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs
src/System.DirectoryServices.AccountManagement/tests/PrincipalTest.cs
src/System.DirectoryServices.AccountManagement/tests/UserPrincipalTest.cs
src/System.Net.Http/tests/FunctionalTests/PostScenarioTest.cs
src/System.Net.Http/tests/UnitTests/DigestAuthenticationTests.cs

Cred PR based on 
https://github.com/dotnet/corefx/pull/43044
and 
https://github.com/dotnet/corefx/pull/43045
Please wait with merge until both above are merged first.

Credentials fixes

---

.config/CredScanSuppressions.json
src/Common/src/Interop/Windows/winhttp/Interop.winhttp_types.cs
src/System.Data.SqlClient/src/System/Data/SqlClient/TdsEnums.cs
src/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/constants.cs

Remove from list in cases where we have a fix pending or an exemption granted w/ inline suppression

Update CredScan suppressions

---

.config/CredScanSuppressions.json

Remove all entries for issues fixed and also for all issues for which exception details are filed in.

Update CredScanSuppressions.json file

---

src/Common/tests/System/Net/Prerequisites/Deployment/setup_certificates.ps1
src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Proxy.cs

Add credscan suppression comments for the following approved exceptions:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100392
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1100969

[Credscan] Add supressions
