mono/corefx

- src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs
_sslStream.dispose causes an unexpected behavior
@marek-safar
> [System.Data] workaround for windows

- src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs
Part of the fix for https://github.com/mono/mono/issues/6350
> Extend SSL System.Data workaround for linux with disabled BTLS

- src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs
Partial fix for https://github.com/mono/mono/issues/6767
Those API used to be public in .NET but are private/internal in .NET Core 
UPD: It looks like those API is public in .NET Core https://github.com/dotnet/corefx/pull/26252/files (merged 12 days ago)
> Make some SqlCommand API public

- src/Common/tests/System/Net/Configuration.Http.cs
We will add a Mono-specific partial implementation for these.
> Add `#if !MONO` conditional around some `System.Net.Test.Common.Configuration.Http` values.

- src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexCompilationInfo.cs
Needed for https://github.com/mono/mono/pull/7363
> [System.Text] Bring back mono-specific attributes to keep API the same

- src/Common/src/CoreLib/System/Collections/Generic/List.cs
Fixes https://github.com/mono/mono/pull/7478
> use Array_ReferenceSources.MaxArrayLength for mono

- src/Common/src/CoreLib/System/Collections/Generic/KeyNotFoundException.cs
- src/Common/src/CoreLib/System/Collections/Generic/List.cs
- src/Common/src/CoreLib/System/Collections/ObjectModel/ReadOnlyCollection.cs
- src/System.Collections/src/System/Collections/BitArray.cs
Needed for https://github.com/mono/mono/pull/7478
> Hide TypeForwarders from mono (Collections)

- src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs
This is so we can fix https://github.com/mono/mono/issues/7975 more easily.
> Disable compiled Regex by default, but allow for it to be turned on.

- src/Common/src/CoreLib/System/Text/StringBuilder.cs
- src/System.Collections/tests/BitArray/BitArray_CtorTests.cs
- src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlDataContract.cs
- src/System.Private.DataContractSerialization/src/System/Xml/XmlCanonicalWriter.cs
A few BitArray tests sometimes fail with OOM - reproduces when there are not enough memory.
Also a few fixes for System.Runtime.Serialization:
XmlDataContract.cs - in all other places in this file System.Linq is used via reflection.
> Skip flaky-tests on mono, runtime.serialization fixes

- src/System.Private.Xml/src/System/Xml/Xslt/XsltException.cs
- src/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/DateTimeHelper.cs
- src/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationFeedFormatter.cs
.NET Core compiles code using empty reference assemblies so it's not required to assign values to value types, but it won't work on mono.
> Remove merge marker, fix CS0177

- src/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs
This fixes [test failures](https://gist.github.com/MaximLipnin/8c19150f5740c9d35bf45a1dad8d2a0b).
Related to https://github.com/mono/mono/issues/8122
Reference to old issue:
Bug: https://bugzilla.xamarin.com/show_bug.cgi?id=12571
Commit: https://github.com/mono/mono/commit/2d573ae1ceac1656f0293cca3736dcb10c28be38#diff-540f710f00de5211a5d25a96cb442d01
> [System.Private.Xml.Linq] port the fix to support existing implementation for converting XElement

- src/Common/src/CoreLib/System/Text/StringBuilder.cs
On the mono interpreter we can't use fault signals for exception throwing.
> Explicitly throw NRE in unsafe StringBuilder.Append

- src/Common/src/CoreLib/System/Text/StringBuilder.cs
> Revert "Explicitly throw NRE in unsafe StringBuilder.Append"

- src/System.Memory/tests/ParsersAndFormatters/TestData.cs
> [System.Memory]: Disable `System.Buffers.Text.Tests.TestData.DecimalTestData` on Mono

- src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs
- src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs
Switch CmsSigner default algorithm to SHA-1 to match documented .NET Framework behaviour. Make EnvelopedCms class partial to allow adding methods to it.
> System.Security.Cryptography.Pkcs

- src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Asn.cs
- src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.DSA.cs
- src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs
- src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfoCollection.cs
- src/System.Security.Cryptography.Pkcs/tests/EnvelopedCms/EdgeCasesTests.cs
- src/System.Security.Cryptography.Pkcs/tests/SignedCms/CmsSignerTests.cs
- src/System.Security.Cryptography.Pkcs/tests/SignedCms/SignedCmsTests.cs
Downstream https://github.com/dotnet/corefx/pull/30046
* Return same error code for invalid encoded messages in ContentInfo.GetContentType on Linux/Mac as on Windows.
* Fix compilation of CmsSignature.DSA in non-netcoreapp scenario in the same way as RSA and ECDsa.
* Handle invalid value when CmsSigner.SignerIdentifierType is being assigned in the same was as on .NET Framework.
* Throw correct exception (as documented) for incorrect index values.
> Cherry-pick: System.Security.Cryptography.Pkcs behaviour fixes

- src/Common/src/CoreLib/System/Boolean.cs
- src/Common/src/CoreLib/System/Char.cs
- src/Common/src/CoreLib/System/InvalidTimeZoneException.cs
- src/Common/src/CoreLib/System/TimeZoneNotFoundException.cs
Not sure about `TimeZoneNotFoundException` and `InvalidTimeZoneException` (they had them in mono but with different values)
> Hide more forwarders from corlib on mono

- src/Common/src/CoreLib/System/Number.Formatting.cs
Cherry-pick https://github.com/dotnet/coreclr/pull/18221
For https://github.com/mono/mono/pull/8626#discussion_r194984329
> Fix number formatting exception with empty NumberGroupSizes array

- src/Native/Unix/System.Native/pal_io.c
See: https://github.com/dotnet/corefx/pull/30277
(once merged and submodule bumped, can remove the `XOPEN` hack for CI CPPFLAGS)
> Backport getline fix for AIX to Mono CoreFX

- src/System.Security.Cryptography.ProtectedData/tests/ProtectedDataTests.cs
There is no (and seems won't be) managed implementation for ProtectedData in CoreFX. So related xunit tests are actual only for Windows. To avoid failures on non-windows targets I added [PlatformSpecific(TestPlatforms.Windows)] attribute. That's suggested in https://github.com/mono/mono/issues/9395.
> ProtectedData: make unit test windows-specific

- src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationHost.cs
- src/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs
- src/System.Configuration.ConfigurationManager/src/System/Configuration/TypeUtil.cs
Modified corefx System.Configuration.ConfigurationManager to be Mono machine.config aware and work with System.Configuration.
> Added ability to work with 'legacy' System.Configuration in Mono

- src/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeServerStream.Windows.cs
- src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeClientStream.Windows.cs
- src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Windows.cs
The big commit is cherry-picked from upstream, the small commit is local.
> System.IO.Pipes: Additional changes to implement Windows-specific constructors

- src/Common/src/System/Security/Cryptography/AsnWriter.cs
Only seems to be triggered on big endian; @EgorBo believes it's the
wrong overload, but I'm not sure.
(note to debug DecimalConstant.Emit in mcs later; for now I would
like CI lanes for AIX working again to assess the repercussions
of CoreFX imports)
See mono/mono#9684
> Workaround for mcs issue in AsnWriter

- src/Common/src/CoreLib/System/Reflection/ConstructorInfo.cs
- src/System.Reflection/tests/ConstructorInfoTests.cs
1. It brings back `BindingFlags.CreateInstance` as default value for invokeAttr.
2. It fixes unit test which expects OverflowException and gets TargetInvocationException on invocation array constructor with  negative length
> [System.Reflection] Replace Default binding flag with CreateInstance in Invoke method

- src/Common/src/CoreLib/System/Math.cs
Bring back icall for Math.Round instead of managed implementation since it regresses performance on CPU without SSE41 (with SSE41 managed implementation will be replaced).
Needed for https://github.com/mono/mono/pull/10033
> Use icall for Math.Round

- src/System.Runtime/tests/System/Reflection/MemberInfoTests.netcoreapp.cs
Relates to https://github.com/mono/mono/pull/9746
The issues:
- https://github.com/mono/mono/issues/10127
- https://github.com/mono/mono/issues/10129
> [Reflection] Skip some xunit tests for HasSameMetadataDefinitionAs

- src/System.Runtime/tests/System/Reflection/MemberInfoTests.netcoreapp.cs
Relates to https://github.com/mono/mono/pull/9746.
The issue: https://github.com/mono/mono/issues/10159
> [Reflection] Skip HasSameMetadataDefinitionAs_CornerCase_CLSIDConstructor xunit test

- src/Native/Unix/Common/pal_config.h.in
- src/Native/Unix/System.Native/pal_errno.c
- src/Native/Unix/System.Native/pal_io.c
- src/Native/Unix/System.Native/pal_maphardwaretype.c
- src/Native/Unix/System.Native/pal_networking.c
- src/Native/Unix/System.Native/pal_tcpstate.c
Been a while since I last tested, but the changes have gotten merged in upstream. This syncs them over, covers parts upstream removed, etc.
Minor tweaks to update checks (sockio.h, if it isn't covered already, and utsname.domainname) in the root module if the submodule is updated would be needed. See dotnet/corefx#31083
> CoreFX PAL for Haiku

- src/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.cs
To be able to override it in RegistryKey.FileSystem implementation, needed for https://github.com/mono/mono/pull/9855
All other platform-specific methods also have "Core" as a suffix in this type.
> Add CloseCore to RegistryKey

- src/System.Runtime/tests/System/Reflection/MemberInfoTests.cs
Relates to https://github.com/mono/mono/pull/9746
The issues:
- https://github.com/mono/mono/issues/10276
- https://github.com/mono/mono/issues/10277
> [Reflection] Skip TestGenericMethodsInheritTheReflectedTypeOfTheirTemplate and TestInheritedEventAccessors xunit tests

- src/System.Runtime/tests/System/Reflection/MemberInfoTests.netcoreapp.cs
Relates to https://github.com/mono/mono/pull/9746
> Use  SkipOnTargetFramework instead of normal Skip to fix xunit issue

- src/System.Reflection/tests/FieldInfoTests.cs
Relates to #https://github.com/mono/mono/pull/10370
The issue: https://github.com/mono/mono/issues/10372
> [Reflection] Skip SetValueDirect_GetValueDirectRoundDataTest 

- src/Native/Unix/System.Native/pal_networking.c
Fixes https://github.com/mono/mono/issues/9439
IMO it should throw NotSupported error instead of hidden no-op, shouldn't it?
Does it make sense to upstream this change as it seems the minimal Linux Kernel version .NET Core officially supports is 3.14 ? (`SO_REUSEPORT` was introduced in 3.9)
cc @nealef
> Fix compilation errors on Linux kernel < 3.9 (SO_REUSEPORT is not defined)

- src/Common/src/CoreLib/System/Reflection/EventInfo.cs
Relates to https://github.com/mono/mono/pull/10770.
The changes:
- made the class abstract; 
- updated EventHandlerType property to use `GetParametersInternal`; 
- excluded AddEventHandler property; existing Mono-implementation will be used due to some runtime dependencies.
> [Reflection] Preparing EventInfo to import to MONO

- src/System.Reflection/tests/TypeInfoTests.cs
Relates to https://github.com/mono/mono/pull/10871
The changes:
- updated IsEnumDefined_Invalid test with non-empty expected ParamName value on Mono; 
- excluded a failing test case for non-generic interface array in IsAssignableFrom test.
> [Reflection] Update TypeInfo tests

- src/System.Runtime/tests/System/Reflection/FieldInfoTests.cs
Relates to https://github.com/mono/mono/pull/10370
> [Reflection] Exclude CAS-related test from FieldInfoTests on Mono

- src/Common/src/CoreLib/System/CurrentSystemTimeZone.cs
- src/Common/src/CoreLib/System/DateTime.cs
- src/Common/src/CoreLib/System/DateTimeOffset.cs
- src/Common/src/CoreLib/System/Globalization/DateTimeFormat.cs
- src/Common/src/CoreLib/System/Globalization/DateTimeFormatInfo.cs
- src/Common/src/CoreLib/System/Globalization/DateTimeParse.cs
- src/Common/src/CoreLib/System/TimeZone.cs
- src/Common/src/CoreLib/System/TimeZoneInfo.cs
we are not planning to import underlying CultureInfo and CultureData so I had to apply a few changes (they don't brake corefx code)
> Prepare DateTime and TimeZone to be consumed by mono

- src/System.Reflection/tests/GetTypeTests.cs
Issue https://github.com/mono/mono/issues/11269.
Relates to https://github.com/mono/mono/pull/11221.
> Skip GetType reflection test in case when test method takes type full name in upper case and ignoring case flag.

- src/Common/src/CoreLib/System/Reflection/Module.cs
- src/System.Reflection/tests/ModuleTests.cs
- src/System.Reflection/tests/TypeInfoTests.netcoreapp.cs
- src/System.Runtime/tests/System/Reflection/ModuleTests.cs
- src/System.Runtime/tests/System/Reflection/PointerTests.cs
Relates to https://github.com/mono/mono/pull/11577
This PR contains changes required to prepare Module type for the import to Mono.
The changes:
- made Module class partial;
- disabled failing CustomAttributes test in ModuleTest fixture (https://github.com/mono/mono/issues/11569);
- disabled assertion for property info equality in CustomAttributes method of ModuleTests fixture (https://github.com/mono/mono/issues/11572);
- updated Name and TestToString methods of ModuleTests fixture to verify Mono module name instead of CoreFX one;
-  disabled GetField, GetFields and GetTypes methods of ModuleTests fixture due to runtime crash. I didn't find good reprosteps for that besides executing those tests;
- some tests in ModuleTests fixture depend on PointerTests fixture class. Enabling that class …
> [Reflection] Prepare Module type for the import to Mono

- src/Common/src/CoreLib/System/Reflection/Module.cs
Relates to https://github.com/mono/mono/pull/11577
> [reflection] Make Module's GetModuleHandleImpl method internal on Mono as it's CoreRT change only

- src/Common/src/CoreLib/System/Text/DecoderBestFitFallback.cs
- src/Common/src/CoreLib/System/Text/EncoderBestFitFallback.cs
- src/Common/src/CoreLib/System/Text/Latin1Encoding.cs
- src/Common/src/CoreLib/System/Text/UTF32Encoding.cs
- src/Common/src/CoreLib/System/Text/UTF7Encoding.cs
- src/Common/src/CoreLib/System/Text/UTF8Encoding.cs
- src/Common/src/CoreLib/System/Text/UnicodeEncoding.cs
Did not notice these types because they are not public thus not part of the public API (api-diff).
Tested via:
```csharp
foreach (var encoding in Encoding.GetEncodings().Select(e => Encoding.GetEncoding(e.Name)))
{
var serializer = new BinaryFormatter();
using (var ms = new MemoryStream())
{
serializer.Serialize(ms, encoding);
ms.Position = 0;
var clone = (Encoding)serializer.Deserialize(ms);
Assert.Equals(encoding, clone);
}
}
```
in mono
https://github.com/mono/mono/issues/11529
> Make all Encoding types serializable

- src/Common/src/CoreLib/System/Type.cs
Relates to https://github.com/mono/mono/pull/11665
The changes:
- excluded `ReflectionOnlyGetType` method to preserve Mono's implementation;
- replaced `IsMarshalByRefImpl` method with referencesource  implementation the error `System.ArgumentException: object must be MarshalByRef` occurs.
> Fix Type on Mono

- src/Common/src/CoreLib/System/Type.cs
- src/System.Runtime/tests/System/TypeTests.cs
- src/System.Runtime/tests/System/TypeTests.netcoreapp.cs
Relates to https://github.com/mono/mono/pull/11665.
The changes:
- moved IsContextfulImpl method from referencesource to fix `MonoTests.System.Reflection.Emit.TypeBuilderTest.TestIsContextful`;
- changed Module property from `new` to `override` to avoid API change.
- disabled some test cases in TypeTests.cs and TypeTests.netcoreapp.cs (https://github.com/mono/mono/issues/11684, https://github.com/mono/mono/issues/11692, https://github.com/mono/mono/issues/11693)
> [reflection] Changes in Type.cs, TypeTests.cs and TypeTests.netcoreapp.cs

- src/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs
- src/System.IO.FileSystem/tests/DirectoryInfo/MoveTo.cs
Fixes https://github.com/dotnet/corefx/issues/33490
Already accepted upstream: https://github.com/dotnet/corefx/pull/33496
Required for https://github.com/mono/mono/pull/11342
> Re-initialize DirectoryInfo.Name after a MoveTo() operation

- src/System.Reflection/tests/ModuleTests.cs
- src/System.Reflection/tests/TypeInfoTests.netcoreapp.cs
- src/System.Runtime/tests/System/TypeTests.cs
Relates to https://github.com/mono/mono/pull/11665
> Avoid test data conflict between TypeTests and ModuleTests

- src/Common/src/CoreLib/System/Reflection/SignatureConstructedGenericType.cs
- src/Common/src/CoreLib/System/Type.cs
Relates to https://github.com/mono/mono/pull/11665
> Align Type with upstream to support Type.MakeGenericSignatureType()

- src/Common/src/CoreLib/System/Text/DecoderReplacementFallback.cs
- src/Common/src/CoreLib/System/Text/EncoderReplacementFallback.cs
- src/Common/src/System/Drawing/ColorTable.cs
Needed for https://github.com/mono/mono/issues/11663
In order to reduce changes-diff I decided to fix the issue using `ISerializable` impl instead of renamings.
SystemColors changes is required for us (the change is upstreamed: https://github.com/dotnet/corefx/pull/33520).
> Fix binary compatibility with old mono for Encodings. 

- src/System.Runtime/tests/System/TypeTests.cs
For some TypeTestsExtended tests we need to load TestAssembly.dll not from 
current directory but from profile-specific one (`mcs/class/lib/<PROFILE>/tests`).
Relates to https://github.com/mono/mono/pull/11665
> Fix TestAssembly.dll path

- src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAPKCS1SignatureDeformatter.cs
- src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAPKCS1SignatureFormatter.cs
Cherry-picking upstream https://github.com/dotnet/corefx/pull/31568.
This is functionally the same, but helps Mono with a layering problem.
(cherry picked from commit 58a310782b805df19a3939b12544c39296db5ed3)
> Use CryptoConfig.MapNameToOid instead of OID.FromFriendlyName

- src/Common/src/CoreLib/System/Text/DecoderReplacementFallback.cs
- src/Common/src/CoreLib/System/Text/EncoderReplacementFallback.cs
A small addition to https://github.com/mono/corefx/pull/204
There is a small chance of a failure if users serialized their encodings using some recent mono and probably want to be able to deserialize it with mono vNext.
> Encoding: Improve serialization 

- src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/CryptoConfigForwarder.cs
- src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithm.cs
Applying upstream https://github.com/dotnet/corefx/pull/33705.
Forward HashAlgorithm.Create() to a new CryptoConfigForwarder.CreateDefaultHashAlgorithm().
In Mono, `HashAlgorithm.Create()` returns a default algorithm instead of throwing PNSE;
this allows us use a custom version of `CryptoConfigForwarder` to keep compatibility.
> Forward HashAlgorithm.Create() to a new CryptoConfigForwarder.CreateDefaultHashAlgorithm().

- src/System.Runtime/tests/System/Reflection/MethodBaseTests.cs
Relates to https://github.com/mono/mono/pull/11837
> Disable TestMethodBody test in MethodBaseTests fixture

- src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs
.NET Core has two slightly different `Interop.ReadDir.cs` files, one for TimeZoneInfo and one for FileSystemWatcher. This PR merges them (will upstream it).
> Merge two Interop.ReadDir.cs

- src/Native/AnyOS/brotli/common/constants.h
- src/Native/AnyOS/brotli/dec/decode.c
- src/Native/AnyOS/brotli/enc/encode.c
- src/System.IO.Compression.Brotli/tests/BrotliEncoderTests.cs
some tests use that bug and don't initialize structures (because of reference assemblies where those structs are empty) and it doesn't compile under mono.
Added DLLEXPORT. I added that macro to `constant.h` instead of just referencing `#include pal_compiler` in case if we decide to move to a separate file.
Needed for https://github.com/mono/mono/pull/12189
> Make Brotli more mono frienly

- src/Common/src/Interop/Windows/kernel32/Interop.ReadDirectoryChangesW.cs
This fixes a build issue `D:\j\workspace\x\external\corefx\src\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs(158,21): error CS1503: Argument 3: cannot convert from 'uint' to 'int'`. 
It's due to https://github.com/mono/corefx/pull/225/files#diff-a1c7bb639ce6ccca85ec565c2b27664aR51.
Relates to https://github.com/mono/mono/pull/12197
> Fix build issue with FileSystemWatcher on Windows

- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
@lambdageek  helped to investigate an issue:  https://github.com/mono/mono/pull/12197#issuecomment-450197600
It looks like CoreCLR doesn't run finalizers on shutdown so it's probably some codepath that doesn't get tested (but initially it was presented in upstream PR https://github.com/dotnet/corefx/pull/33865#discussion_r242200515)
Stacktrace:
```
CSC     [net_4_x-macos] System.Web.Extensions_standalone_test_net_4_x.dll
MONO_PATH="./../../class/lib/net_4_x-macos:./../../class/lib/net_4_x-macos/tests:.:$MONO_PATH" /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/runtime/mono-wrapper --debug  ../System.Web/Test/tools/standalone-runner.exe System.Web.Extensions_standalone_test_net_4_x.dll
Running tests:
[.Stacktrace:
at <unknown> <0xffffffff>
at (wrapper managed-to-native) …
```
> Avoid a crash in FileSystemWatcher when UnscheduleFromRunLoop is called from the finalizer on shutdown

- src/Common/src/CoreLib/Interop/Unix/System.Native/Interop.ReadDir.cs
- src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs
- src/System.IO.Compression.Brotli/src/System/IO/Compression/dec/BrotliDecoder.cs
- src/System.IO.Compression.Brotli/src/System/IO/Compression/enc/BrotliEncoder.cs
- src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs
1) Apply changes https://github.com/dotnet/coreclr/pull/21622 (allows to safely use the same Interop.ReadDir.cs for both TimeZonInfo and FileSystemWatcher
2) Add `mcs` hacks to Brotli-related types.
mcs doesn't compile this:
```csharp
var data = new byte[2000];
fixed (byte* ptr = data)
byte** ptrptr = &ptr;
```
> Apply Interop.ReadDir.cs changes from the upstream and fix mcs issues

- src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs
- src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs
- src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.Unix.cs
- src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs
- src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs
- src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs
- src/System.Net.Http/tests/UnitTests/HttpEnvironmentProxyTest.cs
This PR brings a few Mono-specific changes that are required to adopt the HttpClient from CoreFX.
- MCS compilation in `HttpConnectionPool`.
- BTLS does not support certificate revocation checks.
- AppleTls does not support the `X509Chain`.
- We do not allow `Ssl2` and `Ssl3`.
TODO:
> "Imperial Red": Mono-specific changes for HttpClient

- src/Common/src/Interop/OSX/Interop.EventStream.cs
- src/Common/src/Interop/Windows/kernel32/Interop.ReadDirectoryChangesW.cs
- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs
- src/System.IO.FileSystem.Watcher/tests/System.IO.FileSystem.Watcher.Tests.csproj
- src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs
- src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs
Backport of changes related to https://github.com/mono/mono/issues/11635 to mono-2018-08 branch.
This will require corefx submodule bumping in 2018-08 branch of mono repo.
Initially the changes were brought to mono master branch with https://github.com/mono/mono/pull/12197.
> Backport of changes related to FileSystemWatcher problem in VSMac to mono-2018-08

- src/Common/src/Interop/OSX/Interop.EventStream.cs
- src/Common/src/Interop/Windows/kernel32/Interop.ReadDirectoryChangesW.cs
- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs
- src/System.IO.FileSystem.Watcher/tests/System.IO.FileSystem.Watcher.Tests.csproj
- src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs
- src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs
Backport of changes related to https://github.com/mono/mono/issues/11635 to mono-2018-10 branch.
This will require corefx submodule bumping in 2018-10 branch of mono repo.
Initially the changes were brought to mono master branch with https://github.com/mono/mono/pull/12197.
> Backport of changes related to FileSystemWatcher problem in VSMac to mono-2018-10

- src/Common/src/Interop/OSX/Interop.EventStream.cs
- src/Common/src/Interop/Windows/kernel32/Interop.ReadDirectoryChangesW.cs
- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs
- src/System.IO.FileSystem.Watcher/tests/System.IO.FileSystem.Watcher.Tests.csproj
- src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs
- src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs
Backport of changes related to https://github.com/mono/mono/issues/11635 to mono-2018-12 branch.
This will require corefx submodule bumping in 2018-12 branch of mono repo.
Initially the changes were brought to mono master branch with https://github.com/mono/mono/pull/12197.
> Backport of changes related to FileSystemWatcher problem in VSMac to mono-2018-12

- src/Common/src/CoreLib/System/ComponentModel/DefaultValueAttribute.cs
From https://github.com/dotnet/corefx/pull/31773
> Add TypeConverter fallback to DefaultValueAttribute

- src/Common/src/System/Net/IPv6AddressHelper.Common.cs
- src/System.Net.Primitives/src/System/Net/IPAddressParser.cs
`IPAddress.Parse("fe80::e8b0:63ff:fee8:6b3b%awdl0")` will crash in .NET Core.
See https://github.com/dotnet/corefx/issues/27529
Will upstream the fix.
> IPAddressParser doesn't accept non-numbers as zoneid

- src/Common/src/CoreLib/System/DateTimeOffset.cs
- src/Common/src/CoreLib/System/Double.cs
- src/Common/src/CoreLib/System/Globalization/TimeSpanParse.cs
- src/Common/src/CoreLib/System/Single.cs
- src/Common/src/CoreLib/System/TimeSpan.cs
- src/System.Data.Common/src/System/Data/DataSet.cs
Needed for https://github.com/mono/mono/pull/13022
(CoreCLR PR: https://github.com/dotnet/coreclr/pull/18645)
> Make primitive types readonly

- src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs
- src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs
We already replaced `IsSsl2AndSsl3Supported` with `!IsMono` everywhere else; this was the only place where it was still used.
> Use PlatformDetection.IsMono instead of IsSsl2AndSsl3Supported.

- src/System.Net.Http/src/System/Net/Http/HttpClient.cs
Add new static `HttpClient.CreateDefaultHandler()` and use it in the default constructor.
Mono will provide a custom version in a parial class part, to allow us to replace the default handler in our mobile profiles.
> Introducing HttpClient.CreateDefaultHandler().

- src/System.Reflection/tests/MemberInfoTests.cs
It was disabled in https://github.com/mono/corefx/pull/123 and should be re-enabled due to addressing https://github.com/mono/mono/issues/10277.
> Re-enable InheritedEventAccessors

- src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs
- src/System.Security.Cryptography.Pkcs/tests/SignedCms/SignedCmsTests.cs
They are not supported by Bitcode/Xamarin.WatchOS.
> [System.Security.Cryptography] Remove exception filters from SignedCms

- src/Common/src/CoreLib/System/Globalization/DateTimeFormat.cs
- src/Common/src/CoreLib/System/Globalization/DateTimeFormatInfo.cs
- src/Common/src/CoreLib/System/Globalization/DateTimeParse.cs
- src/System.Runtime/tests/System/DateTimeOffsetTests.cs
- src/System.Runtime/tests/System/DateTimeTests.cs
- src/System.Runtime/tests/System/TimeSpanTests.cs
Add `GlobalizationMode.Invariant` conditionals to some calendar code.
This allows the Japanese, Taiwan and Hebrew calendars to be disabled.
> Add conditionals allowing some calenders to be disabled.

- src/Native/Unix/System.Native/pal_networking.c
Cherrypick dotnet/corefx@991edc840b0240aeb9b245673eb78dc3b80f3a3b
to initialize `header->msg_flags`
Addresses mono/mono#13859
Coverity: 1443505
> [pal_networking] cherrypick flags fix from upstream

- src/System.Linq.Expressions/tests/DebuggerTypeProxy/ExpressionDebuggerTypeProxyTests.cs
- src/System.Linq.Expressions/tests/Dynamic/BindingRestrictionsProxyTests.cs
- src/System.Linq.Expressions/tests/Dynamic/ExpandoObjectProxyTests.cs
These tests failed on Xamarin.iOS since the linker strips out most Debugger* attributes in release builds.
We can gracefully handle this case and simply skip the tests instead.
Port of https://github.com/dotnet/corefx/pull/36785 to the mono corefx fork.
> System.Linq.Expressions: Skip tests if DebuggerTypeProxy attribute isn't available

- src/System.Linq.Expressions/tests/DebuggerTypeProxy/ExpressionDebuggerTypeProxyTests.cs
- src/System.Linq.Expressions/tests/Dynamic/BindingRestrictionsProxyTests.cs
- src/System.Linq.Expressions/tests/Dynamic/ExpandoObjectProxyTests.cs
These tests failed on Xamarin.iOS since the linker strips out most Debugger* attributes in release builds.
We can gracefully handle this case and simply skip the tests instead.
Port of https://github.com/dotnet/corefx/pull/36785 to the mono corefx fork.
Backport of #273.
> [mono-2019-02] System.Linq.Expressions: Skip tests if DebuggerTypeProxy attribute isn\u0027t available

- src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs
System.IO.Filesystem's MoveFile() and ReplaceFile() use link/unlink under some conditions to avoid a copy. This fixes two problems with that:
* MoveFile()'s fall-back does not recognize Android's error as non-critical, and bails out on the fall-back with an exception. From logs We know that 'strerror_r(android_error)' is 'Permission denied' so it should be EACCES (we already check for EPERM)
* While MoveFile() was using a fall-back, ReplaceFile() wasn't.
Backport of #275.
/cc @alexischr
> [master] Use fallbacks when link() fails

- src/System.Threading.ThreadPool/tests/ThreadPoolTests.cs
Only observed a couple of time in CoreFX, corlib-xunit Windows x64 Mono CI,
https://jenkins.mono-project.com/view/Mono/job/z/label=w64/8715/testReport/junit/Test%20collection%20for%20System.Threading.ThreadPools.Tests/ThreadPoolTests/System_Threading_ThreadPools_Tests_ThreadPoolTests_QueueRegisterPositiveAndFlowTest/
Test is using a local variable to set state between threads and very infrequent, the reading thread seems to pick the old value.
Looks like coordination between reader/writer thread works as expected and since this is an infrequent failure, doesn't look like a coordination issues or problem with the ThreadPool (would have expected failures in many tests) implementation.
The test is however using a fragile construction using a local variable (backgroundAsyncLocalValue) to …
> Infrequent failure Mono Windows x64, ThreadPoolTests.QueueRegisterPositiveAndFlowTest.

- src/Common/src/CoreLib/System/Runtime/CompilerServices/RuntimeFeature.cs
Remove the `#if MONO` conditional part of `RuntimeFeature` (`IsDynamicCodeSupported` and `IsDynamicCodeCompiled`) to put it inside corlib.  This will make it easier to modify these constants on a per-platform level without requiring corefx bumps.
> Remove Mono-specific `RuntimeFeature` constants.

- src/Common/tests/System/IO/PathFeatures.cs
- src/Common/tests/System/Net/Capability.Sockets.cs
- src/System.IO.FileSystem/tests/PortedCommon/DllImports.cs
- src/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs
They cause issues on iOS where all p/invokes need to be resolved.
> Remove Windows-specific p/invokes from tests

- src/Common/tests/System/IO/PathFeatures.cs
- src/Common/tests/System/Net/Capability.Sockets.cs
- src/System.IO.FileSystem/tests/PortedCommon/DllImports.cs
- src/System.IO.FileSystem/tests/PortedCommon/ReparsePointUtilities.cs
- src/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs
They cause issues on iOS where all p/invokes need to be resolved.
Backport of #288.
> [mono-2019-02] Remove Windows-specific p/invokes from tests

- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs
/cc @alexischr looks like this wasn't merged when https://github.com/mono/mono/pull/14504 was merged.
> [2019-02][monodroid] Enable building on win32

- src/Common/src/CoreLib/System/Threading/Tasks/TaskExtensions.cs
- src/System.Threading.Tasks/tests/System.Runtime.CompilerServices/ConfiguredCancelableAsyncEnumerableTests.netcoreapp.cs
Those were moved to TaskAsyncEnumerableExtensions in the upstream (our fork doesn't have it)
And copy-paste `ConfiguredCancelableAsyncEnumerableTests.netcoreapp.cs ` tests from the upstream
> Remove some methods from TaskExtensions

- src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs
- src/Common/src/CoreLib/System/Memory.cs
- src/Common/src/CoreLib/System/ReadOnlyMemory.cs
- src/Common/src/CoreLib/System/ReadOnlySpan.Fast.cs
- src/Common/src/CoreLib/System/Span.Fast.cs
- src/Common/src/CoreLib/System/String.Manipulation.cs
- src/Common/src/CoreLib/System/String.cs
- src/System.ComponentModel.TypeConverter/src/System/ComponentModel/BaseNumberConverter.cs
These changes were rejected in the upstream
1) Index+Range in Span/Memory: https://github.com/dotnet/standard/commit/77258cd9b6f9275e5d91d21d0a790579be14d1d1 (also, were removed from coreclr)
2) Batch operations in Collection: https://github.com/dotnet/standard/pull/1222 (also being removed in coreclr now)
3) BaseNumberConverter should have internal ctor.
> Synchronize NS21 changes with upstream

- src/System.ComponentModel.TypeConverter/src/System/ComponentModel/BaseNumberConverter.cs
These changes were rejected in the upstream
1) Index+Range in Span/Memory: https://github.com/dotnet/standard/commit/77258cd9b6f9275e5d91d21d0a790579be14d1d1 (also, were removed from coreclr)
2) Batch operations in Collection: https://github.com/dotnet/standard/pull/1222 (also being removed in coreclr now)
3) BaseNumberConverter should have internal ctor.
Backport of #294.
/cc @marek-safar @EgorBo
> [mono-2019-02] Synchronize NS21 changes with upstream

- src/System.Net.Http/src/System/Net/Http/HttpClient.cs
- src/System.Net.Http/tests/FunctionalTests/HttpRequestMessageTest.cs
Backport of https://github.com/dotnet/corefx/pull/38129.
* HttpClient.SendAsync() should not attempt to read response body on a HEAD request.
(cherry picked from commit 73e610f847f9c5100a0cec4a80692969836ff35d)
The description of the upstream PR mentions "HEAD and PUT request" - this was my original approach, which was discussed during code review and then changed into only doing it for HEAD.  Thanks a lot to @kg for pointing this out.
> HttpClient.SendAsync() should not attempt to read response body on a HEAD request.

- src/System.Net.Http/src/System/Net/Http/HttpClient.cs
- src/System.Net.Http/tests/FunctionalTests/HttpRequestMessageTest.cs
Backport of https://github.com/dotnet/corefx/pull/38129.
* HttpClient.SendAsync() should not attempt to read response body on a HEAD request.
(cherry picked from commit 73e610f847f9c5100a0cec4a80692969836ff35d)
The description of the upstream PR mentions "HEAD and PUT request" - this was my original approach, which was discussed during code review and then changed into only doing it for HEAD.  Thanks a lot to @kg for pointing this out.
Backport of #297.
/cc @akoeplinger @baulig
> [mono-2019-02] HttpClient.SendAsync() should not attempt to read response body on a HEAD request.

- src/System.Net.Http/tests/FunctionalTests/HttpRequestMessageTest.cs
The test was done against corefx/master and does not compile with our fork because of changes in their `LoopbackServer` as well as a new `HttpClientTestBase` subclass that was introduced in master.
> Remove the newly added test again.

- src/System.Net.Http/tests/FunctionalTests/HttpRequestMessageTest.cs
The test was done against corefx/master and does not compile with our fork because of changes in their `LoopbackServer` as well as a new `HttpClientTestBase` subclass that was introduced in master.
Backport of #300.
/cc @akoeplinger @baulig
> [mono-2019-02] Remove the newly added test again.

- src/Common/src/CoreLib/System/Globalization/DateTimeFormatInfo.cs
- src/Common/src/CoreLib/System/Globalization/DateTimeParse.cs
The goal is to allow the linker to remove some of the globalization code
that is conditional to `GlobalizationMode.Invariant`.
Since the linker does not currently support dead code elimination, it cannot
break down any conditionals inside method bodies.  One trick that we use to
work around this is to move those conditional pieces into separate methods;
then we can give the linker a list of those methods and tell it to replace
their bodies with exceptions.
In this particular case, we do not want to access the `JapaneseCalendar` and
`TaiwanCalendar` types from methods that could not (currently) be linked out.
The `DateTimeFormatInfo.PopulateSpecialTokenHashTable()` method does not
explicitly reference any of those, but it is quite big so we benefit from
having the non-invariant pieces in a …
> Make `DateTimeFormatInfo` and `DateTimeParse` more linker friendly.

- src/Common/src/CoreLib/System/Reflection/PropertyInfo.cs
As per https://github.com/mono/mono/issues/14864
Note that this is a Mono CoreFX change only.
> Marks PropertyInfo as [Serializable]

- src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs
Relates to https://github.com/mono/mono/issues/13065.
The fix is suggested in https://github.com/dotnet/SqlClient/issues/58.
> Fix the issue where SQL connection hangs with zero-connection timeout

- src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs
- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs
Fixes https://github.com/mono/mono/issues/15434 by checking if the path is effectively empty before interacting with any Path methods.
We needed to modify the fork at this point because Mono still supports
netfx Path rules, which cannot contain spaces (CoreFX allows this on nix).
> Add Empty Path Check to the Start of FileSystemWatcher Notify Events

- src/System.Numerics.Vectors/tests/GenericVectorTests.cs
- src/System.Numerics.Vectors/tests/GenericVectorTests.tt
This allows us to use the test with the managed linker enabled in Xamarin.iOS
since it no longer strips out the MaxValue/MinValue fields.
See mono/mono#14877
Port of upstream corefx PR https://github.com/dotnet/corefx/pull/39095
> System.Numerics.Vectors: Remove reflection in GenericVectorTests

- src/System.Net.Security/tests/FunctionalTests/ServerNoEncryptionTest.cs
Mono ignores the `EncryptionPolicy` enum and always requires encryption, so we should disable this entire test class.
> Disable the entire ServerNoEncryptionTest test.

- src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs
- src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs
- src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpContentReadStream.cs
Cherry-picking CoreFX PR https://github.com/dotnet/corefx/pull/37391.
* Log exceptions from asynchronously failing Expect: 100-continue sends
When Expect: 100-continue is used, the sending of the request body content is allowed to run concurrently with the receipt of the response headers.  If the processing of the response headers encounters an exception, we currently fail to ever join with that send task, which results in a TaskScheduler.UnobservedTaskException event.  This PR changes to observe the exception in such cases and log it.
(In doing so, I also came across an async void method, and changed all of the remaining ones in the assembly to be async Task instead.  The current implementation of async void isn't any cheaper than async Task, and is actually more expensive in certain …
> Pick CoreFx #37391: Log exceptions from asynchronously failing Expect: 100-continue sends

- src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs
- src/Common/src/CoreLib/System/TimeZoneInfo.cs
Port of https://github.com/dotnet/coreclr/pull/18305 via https://github.com/dotnet/corefx/pull/30217
Relates to https://github.com/mono/mono/issues/15887
> Skip old time zones adjustments with offsets higher than 14h

- src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs
mcs has problems with this new C# feature: "error CS1644: Feature `pattern matching' cannot be used because it is not part of the C# 7.3 language specification"
> FileSystem.Unix.cs: use "== null" instead of "is null"

- src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs
- src/Common/src/CoreLib/System/TimeZoneInfo.cs
Port of https://github.com/dotnet/coreclr/pull/18305 via https://github.com/dotnet/corefx/pull/30217
Relates to https://github.com/mono/mono/issues/15887
Backport of #313.
/cc @akoeplinger @MaximLipnin
> [mono-2019-02] Skip old time zones adjustments with offsets higher than 14h

- src/System.IO.FileSystem/tests/File/Copy.cs
- src/System.IO.FileSystem/tests/File/Move.cs
This was a bug in the tests from https://github.com/mono/mono/pull/15616
> Use the proper method for getting fully resolved temporary file paths

- src/System.IO.FileSystem/tests/File/Copy.cs
- src/System.IO.FileSystem/tests/File/Move.cs
This was a bug in the tests from https://github.com/mono/mono/pull/15616
Backport of #332.
> [mono-2019-06] Use the proper method for getting fully resolved temporary file paths

- src/System.IO.FileSystem/tests/File/Copy.cs
- src/System.IO.FileSystem/tests/File/Move.cs
This was a bug in the tests from https://github.com/mono/mono/pull/15616
Backport of #332.
> [mono-2019-08] Use the proper method for getting fully resolved temporary file paths

- src/System.IO.FileSystem/tests/File/Copy.cs
- src/System.IO.FileSystem/tests/File/Move.cs
symlink() doesn't work on TVOS devices.
> Disable DanglingSymlinkMove/Copy tests on TVOS

- src/System.IO.FileSystem/tests/File/Copy.cs
- src/System.IO.FileSystem/tests/File/Move.cs
symlink() doesn't work on TVOS devices.
Backport of #336.
> [mono-2019-08] Disable DanglingSymlinkMove/Copy tests on TVOS

- src/System.IO.FileSystem/tests/File/Copy.cs
- src/System.IO.FileSystem/tests/File/Move.cs
symlink() doesn't work on TVOS devices.
Backport of #336.
> [mono-2019-06] Disable DanglingSymlinkMove/Copy tests on TVOS

- src/System.Net.Http/src/System/Net/Http/HttpClient.cs
The Uri will eventually be combined w/ a base address and will eventually make a proper one.
This restores mono's old Uri + HttpClient behavior, added originally by https://github.com/mono/mono/commit/0b7afa989dafd4d712d5a94044fd98ecc40f2ecc
The issue was logged from: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/967582
It appears that the test that would have caught this was disabled via this commit:
https://github.com/mono/mono/commit/2f411750acfd2132f9b4970ef8cf11d9a0f62df9
> Allow file:// uri's to be provided to HttpClient

- src/System.Net.Http/src/System/Net/Http/HttpClient.cs
The Uri will eventually be combined w/ a base address and will eventually make a proper one.
This restores mono's old Uri + HttpClient behavior, added originally by https://github.com/mono/mono/commit/0b7afa989dafd4d712d5a94044fd98ecc40f2ecc
The issue was logged from: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/967582
It appears that the test that would have caught this was disabled via this commit:
https://github.com/mono/mono/commit/2f411750acfd2132f9b4970ef8cf11d9a0f62df9
Backport of #339.
/cc @akoeplinger @steveisok
> [mono-2019-06] Allow file:// uri's to be provided to HttpClient

- src/System.Net.Http/src/System/Net/Http/HttpClient.cs
The Uri will eventually be combined w/ a base address and will eventually make a proper one.
This restores mono's old Uri + HttpClient behavior, added originally by https://github.com/mono/mono/commit/0b7afa989dafd4d712d5a94044fd98ecc40f2ecc
The issue was logged from: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/967582
It appears that the test that would have caught this was disabled via this commit:
https://github.com/mono/mono/commit/2f411750acfd2132f9b4970ef8cf11d9a0f62df9
Backport of #339.
/cc @akoeplinger @steveisok
> [mono-2019-08] Allow file:// uri's to be provided to HttpClient

- src/System.Net.Sockets/tests/FunctionalTests/NetworkStreamTest.netcoreapp.cs
Disable test NetworkStreamTest.ReadAsync_ContinuesOnCurrentSynchronizeContextIfDesired().
We currently do not run any of the NetworkStream tests; disabling this one will allow us
to do so with my upcoming PR that will use NetworkStream from CoreFX.
> Disable test NetworkStreamTest.ReadAsync_ContinuesOnCurrentSynchronizeContextIfDesired()

- src/System.Drawing.Primitives/src/System/Drawing/Color.cs
We need to ifdef out the `Editor` attribute since System.Drawing.Design is not there on mobile.
> Enable Color TypeConverter on mobile profiles

- src/System.Drawing.Primitives/src/System/Drawing/Color.cs
We need to ifdef out the `Editor` attribute since System.Drawing.Design is not there on mobile.
Backport of #356.
> [mono-2019-08] Enable Color TypeConverter on mobile profiles

- src/System.Drawing.Primitives/src/System/Drawing/Color.cs
We need to ifdef out the `Editor` attribute since System.Drawing.Design is not there on mobile.
Backport of #356.
> [mono-2019-06] Enable Color TypeConverter on mobile profiles

- src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs
Fixing unit test error of xamarin-macios during mono 2019-10 integration
Error:
System.MissingMemberException : The lazily-initialized type does not have a public, parameterless constructor.
Marek suggested to use a factory lambda when calling LazyInitializer.EnsureInitialized.
> Fix System.MissingMemberException

- src/Common/tests/System/Net/Configuration.Http.cs
- src/Common/tests/System/Net/Configuration.Security.cs
- src/Common/tests/System/Net/Configuration.cs
- src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs
- src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs
- src/System.Net.Requests/tests/HttpWebRequestTest.cs
- src/System.Net.WebClient/tests/WebClientTest.cs
- src/System.Net.WebSockets.Client/tests/CloseTest.cs
- src/System.Net.WebSockets.Client/tests/ConnectTest.cs
* Test only fixes *
Port PR #36018 from master branch
This PR changes the Azure test endpoint to use Azure App Service instead of the classic Azure
Cloud Service endpoint. The use of the classic Azure Cloud Service is no longer recommended
since it is harder to maintain.
Once all remaining branches are converted, we will shut down the corefx-net.cloudapp.net
endpoint.
This PR also includes some other test fixes and tests disabled due to active issues.
> Clean up some tests and move to new Azure endpoint (#41603)

- src/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs
Modifies the RequestUri property on HttpRequestMessage to validate the same way as the constructor does.
It will now call into IsAllowedAbsoluteUri, which adds some mono specific checks.
> Modify Validation in HttpRequestMessage.RequestUri

- src/Native/Unix/System.Native/pal_io.c
The `fchmod()` call should happen first to ensure that the target file has the correct permissions prior to writing into it.
On Android, we make an exception and do not call `fchmod()`.
See https://github.com/mono/mono/issues/17133 for details.
> SystemNative_CopyFile(): move fchmod() call to top and add exception for Android

- src/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/Scheduling.cs
We started to see the `System.Core-xunit` step on CI to hit the timeout of 15 minutes with Linux/ARM64. That was weird, because the step used to be completed in around two minutes. With my local device (jetson board) I wasn't able to reproduce it either; it took around 100s there. We then realized it's specific to the new `taishan` CI machines, which are equipped with 64 cores. Hardcoding `mono_cpu_count` to return 16 restored the performance, however that isn't a viable fix.
Limiting `DefaultDegreeOfParallelism` to 16 fixes it, which is less extreme than limiting `mono_cpu_count ()`, still not ideal though. It seems to boil down to the fact that our non-netcore threadpool implementation doesn't handle a large number of cores well.
`repro.cs`, extracted from here …
> [mono] limit DegreeOfParallelism to 16

- src/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/Scheduling.cs
We only want to change the maximum for the _default_ DOP, but the accepted maximum DOP should remain 512.
> [mono] fixup for c44efe7297f8e11cab157c7e96b998dc936d53b7

- src/System.Net.Http/src/System/Net/Http/Headers/UriHeaderParser.cs
Use `(UriKind)300` (which is the same as setting `MONO_URI_DOTNETRELATIVEORABSOLUTE=true`)
when parsing Uri headers.
> [System.Net.Http]: Add workaround for #17897.

- src/Common/src/CoreLib/Interop/Unix/System.Native/Interop.ReadDir.cs
- src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEntry.Unix.cs
- src/System.IO.FileSystem/tests/Enumeration/ErrorHandlingTests.netcoreapp.cs
- src/System.IO.FileSystem/tests/File/Create.cs
- src/System.IO.FileSystem/tests/FileStream/LockUnlock.cs
Fixes https://github.com/mono/mono/issues/17948
Pulled in upstream change https://github.com/dotnet/corefx/pull/34389
> Backport FixPathLength 255 PR

- src/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs
- src/System.IO.FileSystem/tests/DirectoryInfo/Create.cs
Fixes https://github.com/mono/mono/issues/18291
Backport of https://github.com/dotnet/runtime/commit/db671a853e3c7a3eea5016b2dedf7b1977a17002
> Invalidate DirectoryInfo After Create

- src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs
This should fix mono/mono#18030.
> [Sockets]: Always reset internal SAEA completion when reattempting connection in MultipleConnectAsync.

- src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs
This should fix mono/mono#18030.
Backport of #389.
/cc @baulig
> [mono-2019-12] [Sockets]: Always reset internal SAEA completion when reattempting connection in MultipleConnectAsync.

- src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs
This should fix mono/mono#18030.
Backport of #389.
/cc @baulig
> [mono-2019-10] [Sockets]: Always reset internal SAEA completion when reattempting connection in MultipleConnectAsync.

- src/System.Collections.NonGeneric/tests/HashtableTests.cs
- src/System.Runtime.Extensions/tests/System/BitConverter.cs
HashTableTests.Ctor_Int_Int_GenerateNewPrime and BitConverterTests.ToString_ByteArrayTooLong_Throws
Causes issues on Windows 32bit and other platforms.
> Disable two tests that allocate a lot of memory

- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Move.cs
- src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs
```
* FileSystem.Unix.File.Move use rename in more cases, avoid link/copy when possible, improve performance on file systems that do not support hard links, such as FAT
* Adapt Unit Tests for accounting FileSystemWatcher events fired by FileSystem.Unix.File.Move implementation that use rename in more cases, avoiding link/copy when possible
```
This PR looks to fix the  MonoDevelop.Projects.DotNetCoreFileWatcherTests.AddRenameRemoveSingleFile error described in DevDiv workitem 1089785.
A FileSystemWatcher regression occurred when bots were upgraded from Mojave to Catalina. 
It turns out that File Renamed events were not being sent on Catalina though the files were being properly renamed. 
To fix, a cherry-pick of a commit on `dotnet/corefx` was applied.
Reproduced using desktop mono …
> FileSystem.Unix.File.Move uses "rename" in more cases (#40611)

- src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Move.cs
- src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs
```
* FileSystem.Unix.File.Move use rename in more cases, avoid link/copy when possible, improve performance on file systems that do not support hard links, such as FAT
* Adapt Unit Tests for accounting FileSystemWatcher events fired by FileSystem.Unix.File.Move implementation that use rename in more cases, avoiding link/copy when possible
```
This PR looks to fix the  MonoDevelop.Projects.DotNetCoreFileWatcherTests.AddRenameRemoveSingleFile error described in DevDiv workitem 1089785.
A FileSystemWatcher regression occurred when bots were upgraded from Mojave to Catalina. 
It turns out that File Renamed events were not being sent on Catalina though the files were being properly renamed. 
To fix, a cherry-pick of a commit on `dotnet/corefx` was applied.
Reproduced using desktop mono …
> [mono-2019-12] FileSystem.Unix.File.Move uses "rename" in more cases (#40611)

- src/Common/src/System/Globalization/FormatProvider.Number.cs
- src/System.Runtime.Numerics/tests/BigInteger/parse.netcoreapp.cs
Pick https://github.com/dotnet/corefx/commit/73a3cf567a7b02ce4f984f5b791da19812fd8aa9 to fix https://github.com/mono/mono/issues/19239.
(cherry picked from commit 73a3cf567a7b02ce4f984f5b791da19812fd8aa9)
> Fix BigInteger parsing of substring span (#35185)

- src/System.Net.Http/src/System/Net/Http/Headers/ContentDispositionHeaderValue.cs
- src/System.Net.Http/src/System/Net/Http/Headers/HeaderUtilities.cs
- src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.Digest.cs
- src/System.Net.Http/tests/UnitTests/DigestAuthenticationTests.cs
Backport of https://github.com/dotnet/corefx/pull/36627.
* Fix encoding of Digest authentication headers for servers that don't understand RFC 5987 encoding
* Quote-prefix special characters when encoding Digest headers
* Address PR feedback
> Backport: Fix encoding of Digest authentication headers

- .config/CredScanSuppressions.json
All of these were excluded in upstream corefx/runtime and have nothing concerning
> Add CredScan suppression file

- src/Common/src/CoreLib/Interop/Unix/System.Native/Interop.ReadDir.cs
- src/Native/Unix/System.Native/pal_io.c
For Mono we must loop in managed when opendir/readdir/closedir return EINTR in
order to handle Thread.Abort.
This is because while a thread abort will break syscalls with EINTR, throwing the
ThreadAbortException will only happen when the pinvoke returns.
(Although opendir/readdir/clsoedir are not documented to return EINTR, they do
so on macOS Big Sur under certain conditions, so we will need to add managed looping)
Related to https://github.com/mono/mono/issues/20799
This is needed by https://github.com/mono/mono/pull/21016
> [System.Native] Exclude ReadDir pinvoke wrappers on Mono; handle EINTR
